// Book
export const REQUEST_BOOK = 'REQUEST_BOOK';
export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const ERROR_RECEIVE_BOOK = 'ERROR_RECEIVE_BOOK';
export const REQUEST_SAVE_BOOK = 'REQUEST_SAVE_BOOK';
export const RECEIVE_RESULT_SAVE_BOOK = 'RECEIVE_RESULT_SAVE_BOOK';
export const ERROR_RECEIVE_RESULT_SAVE_BOOK = 'ERROR_RECEIVE_RESULT_SAVE_BOOK';
